#!/bin/bash

######################################################################
# spid3R
# use command spid3R system wide
# command: > spid3R $searchsting1 $searchstring2 $searchstring3
######################################################################

######################################################################
# create 24.10.2017
# last modify: 24.10.2017
# bug or anything: d43M0n23@3xpl0it.com
######################################################################
# TODO
# Search Torrent LIKE 'Nubiles.XXX'
# https://rarbg.to/s/XXX/
# CURL HELP....
# curl -s | grep 1080p > links_1080p
# curl -sL xcoorp.com | grep -oP "http:\/\/(\w.*?)\/"
# https://rarbg.to/torrents.php?search=%221BY-DAY%22%2B%221080%22
# https://rarbg.to/s/%221BY+DAY%22%2B%221080%22/
# https://rarbg.to/s/"1BY+DAY"%2B"1080"/
# GREP HELP
# -P: Interpret PATTERN as a Perl regular expression since \w included in the pattern
# -o: only extract the pattern that match the Perl regex
# -A "Googlebot/2.1 (+http://www.google.com/bot.html)"
# THEORIE:
# 1.Phase = Alle links mit entsprechendem suchmuster der Kategorie speichern.
# 2.Phase = Alle links untersuchen und *.torrent datei speichern.
# 3.Phase = *.torrent datein auf Server spielen wo sie weiter verarbeitet werden.
#
# VERSUCH:
# curl -s -A $BOT https://rarbg.to/s/"1BY+DAY"%2B"1080"/ | grep href=\" | grep "torrent" | grep -o "href=\"\/\(torrent\)" - fail regex
# INSTALL -> https://github.com/banteg/rarbg & run
# WORKS curl -s "http://127.0.0.1:4444/?mode=search&search_string=%221BY-DAY%22+%2B+%221080%22&category=4"
# while read line: https://stackoverflow.com/questions/16317961/how-to-process-each-line-received-as-a-result-of-grep-command
######################################################################
# Bash sTyl3!
clear='\033[0m'			#alle Attribute zurücksetzen
bold='\033[1m'			#Fettschrift
underline='\033[4m'		#Unterstreichen
blinken='\033[5m'		#Blinken
invers='\033[7m'		#inverse Darstellung
black='\033[30m'		#Schriftfarbe schwarz
red='\033[31m'			#Schriftfarbe rot
green='\033[32m'		#Schriftfarbe grün
yell='\033[33m'			#Schriftfarbe gelb
blue='\033[34m'			#Schriftfarbe blau
mag='\033[35m'			#Schriftfarbe magenta
turk='\033[36m'			#Schriftfarbe türkis
white='\033[37m'		#Schriftfarbe weiß
orange='\033[93m'		#Schriftfarbe orange
######################################################################


##Variablen
DATE=$(date +%F)
version=v1.0
vdate=24.10.2017

# Database Backup User
DB_USER='d43M0n23'
DB_PASSWD=''
DB_HOST='3xpl0it.com'
DB_NAME='d43M0n23'

# Local Destination
INSTALL_DIR=/usr/share/spid3R

# torrent Destination
# 2 save output
TORRENT=/$home/spid3R/

if [ ! -d $TORRENT ];then
 mkdir $TORRENT;
fi

# Menu Insert
Xinsert_18="Spandex"

# Base Url
BASEURL="https://rarbg.to/"

# Agent Curl
BOT="Googlebot/2.1 (+http://www.google.com/bot.html)"

# Tools install
#if ! hash searchsploit 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes searchsploit ; fi
#if ! hash msfconsole 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes metasploit-framework ; fi


#INSTALL
if [ ! -d $INSTALL_DIR ]; then
echo -e "\n${green} + -- --=[This is your first run of the spid3R script${clear}"
echo -e "${green} + -- --=[This script will install spid3R under $INSTALL_DIR.${clear}"
echo -e "${green} + -- --=[After install you can use the command 'spid3R' Server/System wide and remove the downloaded git folder${clear}"

sleep 2
mkdir -p $INSTALL_DIR 2> /dev/null
cp -Rf $PWD/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/spid3R
ln -s $INSTALL_DIR/spid3R /usr/bin/spid3R
echo -e "${green} + -- --=[Installation Finish.${clear}"
sleep 2
fi

### FUNCTIONS ###
#Latest release
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/d43M0n23/spid3R/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

#UPDATE NEW VERSION
if [ "$LATEST_VERSION" != "$version" ]; then
echo -e "\n${red}Your Version of Copyspl0it is outdated!${clear}"
echo -e "\n${green}Please use the update function: spid3R --update!${clear}"
sleep 5
fi

#UPDATE
if [ "$1"  = "--update" ]; then
echo -e "\n${turk}You have select the update Feature${clear}"
sleep 2
cd /tmp/
git clone https://github.com/d43M0n23/spid3R.git
cp -Rf spid3R/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/spid3R
ln -s $INSTALL_DIR/spid3R /usr/bin/spid3R
echo -e "\n${green}Update finish.Please restart spid3R.${clear}"
rm -r spid3R
exit
fi

#UNINSTALL
if [ "$1"  = "--deinstall" ]; then
echo -e "\n${turk}You have select the deinstall Feature${clear}"
sleep 2
rm -f /usr/bin/spid3R
cd /usr/share/
rm -r spid3R/
echo -e "\n${turk}deinstall Finish${clear}"
cd
exit
fi

# ---------------
# SCRIPT FUNCTION
# ---------------

#1.1080p full
sh_stage1 () {
echo -e "suche in '1080p'"
curl -s "http://127.0.0.1:4444/?mode=search&search_string=%221080%22&category=4" | egrep 'title|url' > 1080p.txt
#grep title 1080p.txt | while read -r line ; do
 #   echo "Processing $line"
    # your code goes here
#	title=$(grep title)
#title=${title/<title>/}
#title=${title/%</title>/}
#	sed -i "s/title/fuck/g" 1080p.txt
#	cp 1080p.txt 1080p.php
	TABLE="1080p"
#	core=${ip/ip=[::ffff:/}
#	core=${core/%]/}
#	echo $core > ${roaduser}_last.ip.txt
#	oldip=$(cat ${roaduser}_last.ip.txt)
#echo -e "$title\n"
#link=$()
#add_date=$DATE

## MYSQL INSERT
#mysql --host=$DB_HOST --user=$DB_USER --password=$DB_PASSWD --databases $DB_NAME << EOF
#INSERT INTO $TABLE (id, title, link, add_date) VALUES (NULL, "$titel", "$link", "$add_date");
#EOF
## MYSQL ENDE
#done

#while read -r line ; do
#    echo "Processing $line"
    # your code goes here
#done < <(grep xyz abc.txt)

while read -r line ; do
    echo "Processing $line"
    # your code goes here
#    	title=$(grep title)
	title=$line
	tmp_title=${title/<title>/}
	new_title=${tmp_title/%<*/}
	echo $new_title >> title.txt
	echo $new_title
done < <(grep title 1080p.txt)
sleep 3
}

#2.1By-Day
sh_stage2 () {
echo -e "suche in '1By.Day - 1080p'"
curl -s "http://127.0.0.1:4444/?mode=search&search_string=%221BY-DAY%22+%2B+%221080%22&category=4"
}

#3.ATKGalleria
sh_stage3 () {
echo -e "suche in 'ATK.Galleria - 1080p'"
curl -s "http://127.0.0.1:4444/?mode=search&search_string=%221BY-DAY%22+%2B+%221080%22&category=4"
}

#4.ATKExotics
sh_stage4 () {
echo -e "suche in 'ATK.Exotics - 1080p'"
curl -s "http://127.0.0.1:4444/?mode=search&search_string=%221BY-DAY%22+%2B+%221080%22&category=4"
}

#5.ATKHairy
sh_stage5 () {
echo -e "suche in 'ATK.Hairy - 1080p'"
curl -s "http://127.0.0.1:4444/?mode=search&search_string=%221BY-DAY%22+%2B+%221080%22&category=4"
}

#6.Baby.Got.Boobs
sh_stage6 () {
echo -e "suche in 'Baby.Got.Boobs - 1080p'"
curl -s "http://127.0.0.1:4444/?mode=search&search_string=%22BabyGotBoobs%22+%2B+%221080%22&category=4" | egrep 'title|url'
}
#country=$(whois $core  | grep country | cut -d":" -f2)

#7.BigTitsAtWork
#8.BigTitsAtSchool
#9.BoldlyGirls
#10.BumsBesuch
#11.BumsBuero
#12.BurningAngel
#13.CherryPimps
#DDFBusty
#DeviantHardcore
#DigitalPlayground
#DorcelClub
#FootFetishDaily
#GirlsDoToys
#GirlsWay
#HarmonyVision
#HotAndMean
#HotLegsAndFeet
#HouseOfTaboo
#InTheCrack
#Killergram
#MilfsLikeItBig
#MomKnowsBest
#MommyGotBoobs
#MommysGirl
#Pantyhosed4U
#PornMegaLoad
#PornstarPlatinum
#PornStarsLikeItBig
#PureMature
#RKPrime
#ShareMyBF
#TeensLoveHugeCocks
#TeensLikeItBig
#TheRealWorkout
#TheLifeErotic
#VIPArea
#WakeUpNFuck
#WeFuckBlackGirls
#WildOnCam



#for file in *;
#do
#  find "$file" -type f -not -name ".*" | grep .mp4$ | while read file
#  do
#    pfad=$(readlink -f "$file") # kpl. Pfad
#	DirPath=$pfad
#	DirPath="$(dirname $DirPath)"
#	DirPath="$(basename $DirPath)"
#	echo "$DirPath"
#	newtag=${DirPath%.XXX*}
#	newfile=${file%.*}
#	ffmpeg -i $file -c copy -metadata title="$newtag" -metadata comment="$newtag" -y ${newfile}_${owntag}.${mp4tag}
#	echo $file korrigiert.
#	cp $file ${file}.bka # Absicherung
#	rm $file
#  done
#  find "$file" -type f -not -name ".*" | grep .mp4$ | while read file
#  do
#        newfile=${file%_core.*}
#        mv $file ${newfile}.${mp4tag}
#        echo $file verschoben.
#   done
#done


# -------------------------
# FUNTION TO EXIT FRAMEWORK
# -------------------------

sh_exit () {
echo -e "${blue}[*]${white} Exit spiD3R torrent framework...${clear}";
sleep 1
exit
}




# ---------------
# START MAINSTAGE
# ---------------

sh_main () {
echo "nothing" > /dev/null 2>&1
}


# -----------------------------
# MAIN MENU SHELLCODE GENERATOR
# -----------------------------
# Loop forever

while :
do

clear
echo -e '\n'
echo -e "${red}"
echo -e '                .__     .___________  __________ '
echo -e '  ____________  |__|  __| _/\_____  \ \______   \'
echo -e ' /  ___/\____ \ |  | / __ |   _(__  <  |       _/'
echo -e ' \___ \ |  |_> >|  |/ /_/ |  /       \ |    |   \'
echo -e '/____  >|   __/ |__|\____ | /______  / |____|_  /'
echo -e '     \/ |__|             \/        \/         \/ '
echo -e "${clear}"
echo -e "\n${orange} + -- --=[https://3xpl0it.com${clear} ${red}Version ${version}${clear}"
sleep 1
echo -e "\n"


cat <<EOF
rarbg - XXX tracker by d43M0n23

EOF
#echo -e "Latest Release: ${LATEST_VERSION}"
#echo -e "\n"
cat << !

    _____________________________________________________________________
    | OPTION |                  DESCRIPTION(filters)                    |
    ---------------------------------------------------------------------
    |   1    -  1080p full           |  28    -  1080p full             |
    |   2    -  1By.Day              |  29    -  1080p full             |
    |   3    -  ATKGalleria          |  30    -  1080p full             |
    |   4    -  ATKExotics           |  31    -  1080p full             |
    |   5    -  ATKHairy             |  32    -  1080p full             |
    |   6    -  BabyGotBoobs         |  33    -  1080p full             |
    |   7    -  BigTitsAtWork        |  34     - Irgendwas              |
    |   8    -  BigTitsAtSchool      |  35     - Irgendwas              |
    |   9    -  BoldlyGirls          |  36     - Irgendwas              |
    |  10    -  BumsBesuch           |  37     - Irgendwas              |
    |  11    -  BurningAngel         |  38     - Irgendwas              |
    |  12    -  CherryPimps          |  39     - Irgendwas              |
    |  13    -  DDFBusty             |  40     - Irgendwas              |
    |  14    -  DeviantHardcore      |  41     - Irgendwas              |
    |  15    -  DigitalPlayground    |  42     - Irgendwas              |
    |  16    -  FootFetishDaily      |  43     - Irgendwas              |
    |  17    -  GirlsDoToys          |  44     - Irgendwas              |
    |  18    -  ${Xinsert_18}        |  45     - Irgendwas              |
    |  19    -  GirlsWay             |  46     - Irgendwas              |
    |  20    -  GirlsWay             |  47     - Irgendwas              |
    |  21    -  GirlsWay             |  48     - Irgendwas              |
    |  22    -  GirlsWay             |  49     - Irgendwas              |
    |  23    -  GirlsWay             |  50     - Irgendwas              |
    |  24    -  GirlsWay             |  51     - Irgendwas              |
    |  25    -  GirlsWay             |  52     - Irgendwas              |
    |  26    -  GirlsWay             |  53     - Irgendwas              |
    |  27    -  GirlsWay             |  54     - Irgendwas              |
    |                                                                   |
    |   E    -  Exit/close spiD3R                                       |
    ---------------------------------------------------------------------
!

#sleep 1
#echo -e ${white} Chose Your Option${RedF}: ${Reset};
#echo -n "$PrompT"
#read choice
cd $TORRENT;
read -p " Chose Your Option:" choice
	case $choice in
		1) sh_stage1 ;;
		2) sh_stage2 ;;
		3) sh_stage3 ;;
		4) sh_stage4 ;;
		5) sh_stage5 ;;
		6) sh_stage6 ;;
		7) sh_stage7 ;;
		8) sh_stage8 ;;
		9) sh_stage9 ;;
		10) sh_stage10 ;;
		11) sh_stage11 ;;
		12) sh_stage12 ;;
		13) sh_stage13 ;;
		14) sh_stage14 ;;
		15) sh_stage15 ;;
		16) sh_stage16 ;;
		e) sh_exit ;;
		E) sh_exit ;;
		*) echo "\"$choice\": is not a valid Option"; sleep 1 ;;
	esac
done
