#!/bin/bash

######################################################################
# spid3R
# search and copy Exploit from exploit-db 2 metasploit-framework
# Needs searchsploit amd metasploit-framework installed
# script install this tools for you
# First run from github directory ./spid3R ... after install
# use command spid3R system wide
# command: > spid3R $searchsting1 $searchstring2 $searchstring3
######################################################################

######################################################################
# create 16.09.2017
# last modify: 21.09.2017
# bug or anything: d43M0n23@3xpl0it.com
######################################################################

######################################################################

# Bash sTyl3!
clear='\033[0m'			#alle Attribute zurücksetzen
red='\e[31m'			#Schriftfarbe rot
bold='\033[1m'			#Fettschrift
underline='\033[4m'		#Unterstreichen
blinken='\033[5m'		#Blinken
invers='\033[7m'		#inverse Darstellung
black='\033[30m'		#Schriftfarbe schwarz
red='\033[31m'			#Schriftfarbe rot
green='\033[32m'		#Schriftfarbe grün
yell='\033[33m'			#Schriftfarbe gelb
blue='\033[34m'			#Schriftfarbe blau
mag='\033[35m'			#Schriftfarbe magenta
turk='\033[36m'			#Schriftfarbe türkis
white='\033[37m'		#Schriftfarbe weiß
orange='\033[93m'		#Schriftfarbe orange
######################################################################


##Variablen
DATE=$(date +%F)
version=v1.0
vdate=16.09.2017

# Local Destination
INSTALL_DIR=/usr/share/spid3R

# Exploit-db dir
SOURCE_PATH=/usr/share/exploitdb/platforms

# MSF4 - Metasploit user dir
MSF_PATH=$HOME/.msf4/modules/exploits


# Tools install
if ! hash searchsploit 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes searchsploit ; fi
if ! hash msfconsole 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes metasploit-framework ; fi

#INSTALL
if [ ! -d $INSTALL_DIR ]; then
echo -e "\n${green} + -- --=[This is your first run of the spid3R script${clear}"
echo -e "${green} + -- --=[This script will install spid3R under $INSTALL_DIR.${clear}"
echo -e "${green} + -- --=[After install you can use the command 'spid3R' Server/System wide and remove the downloaded git folder${clear}"

sleep 2
mkdir -p $INSTALL_DIR 2> /dev/null
cp -Rf $PWD/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/copysploit
rm -f /usr/bin/spid3R
ln -s $INSTALL_DIR/spid3R /usr/bin/spid3R
echo -e "${green} + -- --=[Installation Finish.${clear}"
sleep 2
fi

### FUNCTIONS ###
#Latest release
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/d43M0n23/spid3R/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

#UPDATE NEW VERSION
if [ "$LATEST_VERSION" != "$version" ]; then
echo -e "\n${red}Your Version of Copyspl0it is outdated!${clear}"
echo -e "\n${green}Please use the update function: spid3R --update!${clear}"
sleep 5
fi

#UPDATE
if [ "$1"  = "--update" ]; then
echo -e "\n${turk}You have select the update Feature${clear}"
sleep 2
cd /tmp/
git clone https://github.com/d43M0n23/spid3R.git
cp -Rf spid3R/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/spid3R
ln -s $INSTALL_DIR/spid3R /usr/bin/spid3R
echo -e "\n${green}Update finish.Please restart spid3R.${clear}"
rm -r spid3R
exit
fi

#UNINSTALL
if [ "$1"  = "--deinstall" ]; then
echo -e "\n${turk}You have select the deinstall Feature${clear}"
sleep 2
rm -f /usr/bin/spid3R
cd /usr/share/
rm -r spid3R/
echo -e "\n${turk}deinstall Finish${clear}"
cd
exit
fi

#START MAINSTAGE
clear
echo -e '\n'
echo -e '${farbe}'
echo -e '                .__     .___________  __________ '
echo -e '  ____________  |__|  __| _/\_____  \ \______   \'
echo -e ' /  ___/\____ \ |  | / __ |   _(__  <  |       _/'
echo -e ' \___ \ |  |_> >|  |/ /_/ |  /       \ |    |   \'
echo -e '/____  >|   __/ |__|\____ | /______  / |____|_  /'
echo -e '     \/ |__|             \/        \/         \/ '
echo -e '${clear}'
echo -e "\n${orange} + -- --=[https://3xpl0it.com${clear} ${red}Version ${version}${clear}"
sleep 1
echo -e "\n"
