#!/bin/bash

######################################################################
# spid3R
# use command spid3R system wide
# command: > spid3R $searchsting1 $searchstring2 $searchstring3
######################################################################

######################################################################
# create 24.10.2017
# last modify: 24.10.2017
# bug or anything: d43M0n23@3xpl0it.com
######################################################################
# TODO
# Search Torrent LIKE 'Nubiles.XXX'
# https://rarbg.to/s/XXX/
# CURL HELP....
# curl -s | grep 1080p > links_1080p
# curl -sL xcoorp.com | grep -oP "http:\/\/(\w.*?)\/"
# https://rarbg.to/torrents.php?search=%221BY-DAY%22%2B%221080%22
# https://rarbg.to/s/%221BY+DAY%22%2B%221080%22/
# https://rarbg.to/s/"1BY+DAY"%2B"1080"/
# GREP HELP
# -P: Interpret PATTERN as a Perl regular expression since \w included in the pattern
# -o: only extract the pattern that match the Perl regex
#
# THEORIE:
# 1.Phase = Alle links mit entsprechendem suchmuster der Kategorie speichern.
# 2.Phase = Alle links untersuchen und *.torrent datei speichern.
# 3.Phase = *.torrent datein auf Server spielen wo sie weiter verarbeitet werden.
#
# VERSUCH:
# curl -s https://rarbg.to/s/"1BY+DAY"%2B"1080"/ | grep href=\" | grep "torrent" | grep -o "href=\"\/\(torrent\)" - fail regex
######################################################################
# Bash sTyl3!
clear='\033[0m'			#alle Attribute zurücksetzen
bold='\033[1m'			#Fettschrift
underline='\033[4m'		#Unterstreichen
blinken='\033[5m'		#Blinken
invers='\033[7m'		#inverse Darstellung
black='\033[30m'		#Schriftfarbe schwarz
red='\033[31m'			#Schriftfarbe rot
green='\033[32m'		#Schriftfarbe grün
yell='\033[33m'			#Schriftfarbe gelb
blue='\033[34m'			#Schriftfarbe blau
mag='\033[35m'			#Schriftfarbe magenta
turk='\033[36m'			#Schriftfarbe türkis
white='\033[37m'		#Schriftfarbe weiß
orange='\033[93m'		#Schriftfarbe orange
######################################################################


##Variablen
DATE=$(date +%F)
version=v1.0
vdate=24.10.2017

# Local Destination
INSTALL_DIR=/usr/share/spid3R

# torrent Destination
TORRENT=/$home/spid3R/

# Base Url
BASEURL="https://rarbg.to/"

# Tools install
#if ! hash searchsploit 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes searchsploit ; fi
#if ! hash msfconsole 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes metasploit-framework ; fi

#INSTALL
if [ ! -d $INSTALL_DIR ]; then
echo -e "\n${green} + -- --=[This is your first run of the spid3R script${clear}"
echo -e "${green} + -- --=[This script will install spid3R under $INSTALL_DIR.${clear}"
echo -e "${green} + -- --=[After install you can use the command 'spid3R' Server/System wide and remove the downloaded git folder${clear}"

sleep 2
mkdir -p $INSTALL_DIR 2> /dev/null
cp -Rf $PWD/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/spid3R
ln -s $INSTALL_DIR/spid3R /usr/bin/spid3R
echo -e "${green} + -- --=[Installation Finish.${clear}"
sleep 2
fi

### FUNCTIONS ###
#Latest release
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/d43M0n23/spid3R/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

#UPDATE NEW VERSION
if [ "$LATEST_VERSION" != "$version" ]; then
echo -e "\n${red}Your Version of Copyspl0it is outdated!${clear}"
echo -e "\n${green}Please use the update function: spid3R --update!${clear}"
sleep 5
fi

#UPDATE
if [ "$1"  = "--update" ]; then
echo -e "\n${turk}You have select the update Feature${clear}"
sleep 2
cd /tmp/
git clone https://github.com/d43M0n23/spid3R.git
cp -Rf spid3R/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/spid3R
ln -s $INSTALL_DIR/spid3R /usr/bin/spid3R
echo -e "\n${green}Update finish.Please restart spid3R.${clear}"
rm -r spid3R
exit
fi

#UNINSTALL
if [ "$1"  = "--deinstall" ]; then
echo -e "\n${turk}You have select the deinstall Feature${clear}"
sleep 2
rm -f /usr/bin/spid3R
cd /usr/share/
rm -r spid3R/
echo -e "\n${turk}deinstall Finish${clear}"
cd
exit
fi

# ---------------
# SCRIPT FUNCTION
# ---------------

sh_stage1 () {
echo -e "Controller Status und Config\n"
$corecmd -AdpAllInfo -aAll
}


sh_stage2 () {
echo -e "Ausgabe der Festplatteninformationen\n"
$corecmd -LDInfo -L0 -a0
}


# -------------------------
# FUNTION TO EXIT FRAMEWORK
# -------------------------
sh_exit () {
echo ${BlueF}[*]${white} Exit megaR4id framework...${Reset};
sleep 1
exit
}




# ---------------
# START MAINSTAGE
# ---------------

sh_main () {
echo "nothing" > /dev/null 2>&1
}


# -----------------------------
# MAIN MENU SHELLCODE GENERATOR
# -----------------------------
# Loop forever

while :
do

clear
echo -e '\n'
echo -e "${red}"
echo -e '                .__     .___________  __________ '
echo -e '  ____________  |__|  __| _/\_____  \ \______   \'
echo -e ' /  ___/\____ \ |  | / __ |   _(__  <  |       _/'
echo -e ' \___ \ |  |_> >|  |/ /_/ |  /       \ |    |   \'
echo -e '/____  >|   __/ |__|\____ | /______  / |____|_  /'
echo -e '     \/ |__|             \/        \/         \/ '
echo -e "${clear}"
echo -e "\n${orange} + -- --=[https://3xpl0it.com${clear} ${red}Version ${version}${clear}"
sleep 1
echo -e "\n"


cat <<EOF

megaR4id

EOF

echo -e "Latest Release: ${LATEST_VERSION}"

echo -e "\n"

cat << !

    _____________________________________________________________________
    | OPTION |                  DESCRIPTION(filters)                    |
    ---------------------------------------------------------------------
    |   1    -  1080p full                                              |
    |   2    -  1By-Day                                                 |
    |   3    -  ATK Galleria                                            |
    |   4    -  Baby Got Boobs                                          |
    |   5    -  Redirect browser traffic        -  to google sphere     |
    |   6    -  Sniff browser traffic (http)    -  visited url's        |
    |   7    -  Sniff browser traffic (http)    -  capture pictures     |
    |   8    -  Sniff chat messages   (live)    -  AOL,IRC,YAHOO,MSN    |
    |   9    -  Inject backdoor into (</body>)  -  exe,bat,jar,ps1,dll  |
    |  10    -  Firefox browser heap-spray      -  buffer overflow      |
    |  11    -  Android browser heap-spray      -  buffer overflow      |
    |  12    -  Tor-browser heap-spray(windows) -  buffer overflow      |
    |  13    -  Clone website + keylooger       -  javascritp_keylooger |
    |  14    -  Modem/router login webpage      -  javascritp_keylooger |
    |  15    -  Replace website images          -  img src=http://other |
    |  16    -  Replace website text            -  replace: worlds      |
    |                                                                   |
    |   E    -  Exit/close megaR4id                                     |
    ---------------------------------------------------------------------
!

sleep 1
#echo -e ${white} Chose Your Option${RedF}: ${Reset};
#echo -n "$PrompT"
#read choice

read -p " Chose Your Option:" choice
	case $choice in
		1) sh_stage1 ;;
		2) sh_stage2 ;;
		3) sh_stage3 ;;
		4) sh_stage4 ;;
		5) sh_stage5 ;;
		6) sh_stage6 ;;
		7) sh_stage7 ;;
		8) sh_stage8 ;;
		9) sh_stage9 ;;
		10) sh_stage10 ;;
		11) sh_stage11 ;;
		12) sh_stage12 ;;
		13) sh_stage13 ;;
		14) sh_stage14 ;;
		15) sh_stage15 ;;
		16) sh_stage16 ;;
		e) sh_exit ;;
		E) sh_exit ;;
		*) echo "\"$choice\": is not a valid Option"; sleep 1 ;;
	esac
done
